# Generated by Django 3.1.3 on 2022-07-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='answer', max_length=1000),
        ),
    ]
